# .github/workflows/go_test.yml
# CI (Continuous Integration) workflow for Go projects
# This workflow runs tests on multiple OS and Go versions to ensure cross-platform compatibility
# It executes on every push to main and all pull requests

name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ["1.23.0", "1.23.1", "1.23.2"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: ${{ matrix.go-version }}
          # Cache is disabled because:
          # 1. Currently no external package dependencies
          # 2. No go.sum file exists
          # 3. To avoid warning messages in the workflow
          # Note: Can be enabled when external dependencies are added in the future
          cache: false

      - name: Display Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...